/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ignacio.proyectosensores.GUI;

import com.ignacio.proyectosensores.BLL.ParametrosFaltantesException;
import com.ignacio.proyectosensores.BLL.Protocolo;
import com.ignacio.proyectosensores.BLL.Sensor;
import com.ignacio.proyectosensores.BLL.Tag;
import com.ignacio.proyectosensores.DAL.CodigoRepetidoException;
import com.ignacio.proyectosensores.DAL.SinBaseDatosException;
import com.ignacio.proyectosensores.GUI.creaciones.JPCrearTag;
import com.ignacio.proyectosensores.GUI.util.ProtocoloComboModel;
import java.awt.Frame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ignacio
 */
public class JDModificarTag extends javax.swing.JDialog {

	private Tag tag;
	private Frame parent;
	private ProtocoloComboModel pcb;

	/**
	 * Creates new form JDModificarTag
	 */
	public JDModificarTag(java.awt.Frame parent, boolean modal, Tag t) {
		super(parent, modal);
		this.tag = t;
		this.parent = parent;
		initComponents();
		rellenoComboBox();
		//cb_protocolo.setSelectedItem(t.getProtocolo());
	}

	private void rellenoComboBox() {
		//Obtener los protocolos
		List<Protocolo> a;
		try {
			a = Protocolo.findAll();
			pcb = new ProtocoloComboModel(a);
			cb_protocolo.setModel(pcb);
			cb_protocolo.setSelectedItem(tag.getProtocolo());
		} catch (SinBaseDatosException ex) {
			JOptionPane.showMessageDialog(this, "Sin coneccion a la base datos");
			Logger.getLogger(JPCrearTag.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        b_agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_detalles = new javax.swing.JTextArea();
        cb_protocolo = new javax.swing.JComboBox<>();
        tf_sensorSeleccionado = new javax.swing.JTextField(tag.getSensor().getNombre());
        b_buscarSensor = new javax.swing.JButton();
        s_tiempo = new javax.swing.JSpinner();
        tf_url = new javax.swing.JTextField(tag.getUrl());
        tf_nombre = new javax.swing.JTextField(tag.getNombre());
        b_agregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Sensor asociado:");

        jLabel3.setText("Tiempo actualizacion:");

        jLabel2.setText("URL:");

        jLabel1.setText("Nombre:");

        jLabel5.setText("Protocolo");

        jLabel6.setText("Detalles:");

        b_agregar.setText("Actualizar");
        b_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_agregarActionPerformed(evt);
            }
        });

        ta_detalles.setColumns(20);
        ta_detalles.setRows(5);
        jScrollPane1.setViewportView(ta_detalles);

        cb_protocolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_protocoloActionPerformed(evt);
            }
        });

        tf_sensorSeleccionado.setEditable(false);

        b_buscarSensor.setText("Buscar");
        b_buscarSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buscarSensorActionPerformed(evt);
            }
        });

        s_tiempo.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        s_tiempo.setValue(tag.getSegundos());

        tf_url.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_urlKeyReleased(evt);
            }
        });

        tf_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_nombreKeyReleased(evt);
            }
        });

        b_agregar1.setText("Cancelar");
        b_agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_agregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_sensorSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_buscarSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(s_tiempo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_url, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_protocolo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_agregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(tf_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(s_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(tf_sensorSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_buscarSensor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(cb_protocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_agregar)
                    .addComponent(b_agregar1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_agregarActionPerformed
		try {
			final int segundos = (int) s_tiempo.getValue();
			tag.setSegundos(segundos);
			tag.setDetalle(ta_detalles.getText());
			tag.save();
			JOptionPane.showMessageDialog(this, "Tag Actualizado", "Exito",
					JOptionPane.INFORMATION_MESSAGE);
		} catch (SinBaseDatosException ex) {
			JOptionPane.showMessageDialog(this, "Sin base de datos.");
		} catch (CodigoRepetidoException ex) {
			JOptionPane.showMessageDialog(this, "El codigo ya existe");
		} catch (ParametrosFaltantesException ex) {
			JOptionPane.showMessageDialog(this, "Faltan datos por rellenar",
					"Error", JOptionPane.ERROR_MESSAGE);
		}
		dispose();
    }//GEN-LAST:event_b_agregarActionPerformed

    private void cb_protocoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_protocoloActionPerformed
		final int index = cb_protocolo.getSelectedIndex();
		if (index >= 0) {
			Protocolo p = (Protocolo) pcb.getAt(index);
			tag.setProtocolo(p);
		}
    }//GEN-LAST:event_cb_protocoloActionPerformed

    private void b_buscarSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buscarSensorActionPerformed
		List<Sensor> ls;
		try {
			ls = Sensor.findAllWithDependency();
			for (Sensor s : ls) {
				s.getMaquina().findDependencias();
			}
			JDBuscarSensor b = new JDBuscarSensor(parent, true, ls);
			b.setVisible(true);
			Sensor sensorSeleccionado = b.getSensorSeleccionado();
			if (sensorSeleccionado != null) {
				tag.setSensor(sensorSeleccionado);
				final String nombre = sensorSeleccionado.getNombre();
				if (nombre != null) {
					tf_sensorSeleccionado.setText(nombre);
				}
			}
		} catch (SinBaseDatosException ex) {
			Logger.getLogger(JPCrearTag.class.getName()).log(
					Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_b_buscarSensorActionPerformed

    private void tf_urlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_urlKeyReleased
		final String text = tf_url.getText();
		tag.setUrl(text);
    }//GEN-LAST:event_tf_urlKeyReleased

    private void tf_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nombreKeyReleased
		final String text = tf_nombre.getText();
		tag.setNombre(text);
    }//GEN-LAST:event_tf_nombreKeyReleased

    private void b_agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_agregar1ActionPerformed
		dispose();
    }//GEN-LAST:event_b_agregar1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JDModificarTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JDModificarTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JDModificarTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JDModificarTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				JDModificarTag dialog = new JDModificarTag(new javax.swing.JFrame(), true, new Tag());
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_agregar;
    private javax.swing.JButton b_agregar1;
    private javax.swing.JButton b_buscarSensor;
    private javax.swing.JComboBox<String> cb_protocolo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner s_tiempo;
    private javax.swing.JTextArea ta_detalles;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_sensorSeleccionado;
    private javax.swing.JTextField tf_url;
    // End of variables declaration//GEN-END:variables
}
