package com.ignacio.proyectosensores.GUI;

import com.ignacio.proyectosensores.BLL.Protocolo;
import com.ignacio.proyectosensores.DAL.CodigoRepetidoException;
import com.ignacio.proyectosensores.DAL.SinBaseDatosException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author ignacio
 */
public class JPCrearProtocolo extends javax.swing.JPanel {

	/**
	 * Creates new form JPCrearProtocolo
	 */
	public JPCrearProtocolo() {
		initComponents();
		actualizarTabla();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        b_crear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_protocolo = new javax.swing.JTable();

        jLabel1.setText("Nombre:");

        b_crear.setText("Crear");
        b_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crearActionPerformed(evt);
            }
        });

        t_protocolo.setModel(new ProtocoloTableModel());
        jScrollPane1.setViewportView(t_protocolo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_crear)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(b_crear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crearActionPerformed
		final String text = tf_nombre.getText();
		if (!text.isEmpty()) {
			Protocolo p = new Protocolo(text);
			try {
				p.save();
			} catch (SinBaseDatosException ex) {
				JOptionPane.showMessageDialog(this, "Sin base de datos",
					"Error", JOptionPane.ERROR_MESSAGE);
			} catch (CodigoRepetidoException ex) {
				JOptionPane.showMessageDialog(this, "El codigo ya existe",
					"Error", JOptionPane.ERROR_MESSAGE);
			}
			actualizarTabla();
		}
    }//GEN-LAST:event_b_crearActionPerformed

	public void actualizarTabla() {
		try {
			List<Protocolo> protocolos = Protocolo.findAll();
			ProtocoloTableModel ptm = new ProtocoloTableModel(protocolos);
			t_protocolo.setModel(ptm);
			System.out.println(protocolos);
		} catch (SinBaseDatosException ex) {
			Logger.getLogger(JPCrearLugar.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_crear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_protocolo;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables

	private class ProtocoloTableModel extends AbstractTableModel {

		final List<Protocolo> protocolos;

		public ProtocoloTableModel() {
			protocolos = new ArrayList<>();
		}

		public ProtocoloTableModel(List<Protocolo> protocolos) {
			this.protocolos = protocolos;
		}
		
		@Override
		public int getRowCount() {
			return protocolos.size();
		}

		@Override
		public int getColumnCount() {
			return 1;
		}

		@Override
		public Object getValueAt(int row, int column) {
			return protocolos.get(row);
		}

		@Override
		public String getColumnName(int column) {
			if (column == 0){
				return "Protocolos";
			}else
				return "";
		}

	}
}
